Use ament_export_targets to fix exporting dependencies
ros-planning/warehouse_ros pull request #80
Opened 2021-06-25 13:21 UTC by JafarAbdi

Otherwise, the dependencies will not be exported correctly, this's required for https://github.com/ros-planning/moveit2/pull/514 to pass

2021-06-25 14:19 UTC, vatanaksoytezer commented
This seems to cause compile problems in it's downstreams. See https://github.com/vatanaksoytezer/moveit2/pull/5and it's CI log.

2021-06-25 14:20 UTC, vatanaksoytezer requested changes
This seems to cause compile problems in downstream repos. See https://github.com/vatanaksoytezer/moveit2/pull/5 and the CI log in that PR.

2021-06-26 19:56 UTC, JafarAbdi commented
> This seems to cause compile problems in downstream repos. See [vatanaksoytezer/moveit2#5](https://github.com/vatanaksoytezer/moveit2/pull/5) and the CI log in that PR.

Should be fixed with the last commit

2021-06-26 22:39 UTC, vatanaksoytezer approved these changes
Yep that fixes the issue, thanks!

2021-06-28 20:33 UTC, tylerjw approved these changes
this looks good

2021-06-28 20:33 UTC, merged